/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Athaya_Aufa_Diaz_Tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form Athaya_Aufa_Diaz_Tugas2
     */
    public Athaya_Aufa_Diaz_Tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        soal = new javax.swing.JComboBox<>();
        wujudsoal = new javax.swing.JTextField();
        syaratnya = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Masuka = new javax.swing.JTextField();
        Masukn = new javax.swing.JTextField();
        Masukx = new javax.swing.JTextField();
        Hasil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("STHupo", 0, 36)); // NOI18N
        jLabel1.setText("APROKSIMASI");

        soal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH SOAL", "NO 3", "NO 4", "NO 5" }));
        soal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soalActionPerformed(evt);
            }
        });

        wujudsoal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wujudsoal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        syaratnya.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        syaratnya.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jLabel2.setText("Nilai a");

        jLabel3.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jLabel3.setText("Nilai n");

        jLabel4.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jLabel4.setText("Nilai x");

        jLabel5.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jLabel5.setText("Nilai f(x)");

        Masuka.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Masukn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Masukn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasuknActionPerformed(evt);
            }
        });

        Masukx.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Hasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        jButton3.setText("KELUAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wujudsoal)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Masuka, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(Masukn)
                                    .addComponent(Masukx)
                                    .addComponent(Hasil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(syaratnya)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wujudsoal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(syaratnya, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Masuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Masukn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Masukx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jButton3)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soalActionPerformed
        switch(soal.getSelectedIndex()){
            case 1:
                Masuka.setText(null);
                Masukn.setText(null);
                Masukx.setText(null);
                Hasil.setText(null);
                wujudsoal.setText("f(x) = cosh(-6x)");
                syaratnya.setText("Syarat: a bil real, n bil bulat positif, x bil real");
                break;
            case 2:
                Masuka.setText(null);
                Masukn.setText(null);
                Masukx.setText(null);
                Hasil.setText(null);
                wujudsoal.setText("f(x) = ln(-x)");
                syaratnya.setText("Syarat: a <0, n bilangan bulat positif, x <0");
                break;
            case 3:
                Masuka.setText(null);
                Masukn.setText(null);
                Masukx.setText(null);
                Hasil.setText(null);
                wujudsoal.setText("f(x) = x / (1-x)");
                syaratnya.setText("Syarat: a bil real, n bil bulat positif, -1 < x < 1 ");
                break;
            default:
                Masuka.setText(null);
                Masukn.setText(null);
                Masukx.setText(null);
                Hasil.setText(null);
                wujudsoal.setText(null);
                syaratnya.setText(null);
        }
    }//GEN-LAST:event_soalActionPerformed

    private void MasuknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasuknActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasuknActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double a = Double.parseDouble(Masuka.getText());
        double n = Double.parseDouble(Masukn.getText());
        double x = Double.parseDouble(Masukx.getText());
        switch(soal.getSelectedIndex()){
            case 1:
                Hasil.setText(String.valueOf(PerhitunganSoal3(a,n,x)));
                break;
            case 2:
                if(a<0 && x<0){
                    Hasil.setText(String.valueOf(PerhitunganSoal4(a,n,x)));
                }else{
                    JOptionPane.showMessageDialog(null, "Input yang dimasukkan salah\n"+"Nilai a dan x harus kurang dari 0");
                }
                break;
            case 3:
                if(a!=1 && (x>-1 && x<1)){
                    Hasil.setText(String.valueOf(PerhitunganSoal5(a,n,x)));
                }else{
                    JOptionPane.showMessageDialog(null, "Input yang dimasukkan salah\n"+"Nilai x harus lebih dari -1 dan kurang dari 1");
                }
                break;
            default:
                JOptionPane.showMessageDialog(null, "Masukkan Soal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Masuka.setText(null);
        Masukn.setText(null);
        Masukx.setText(null);
        Hasil.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    public static double PerhitunganSoal3(double a, double n, double x) { 
        double[] f = new double[100001];
        f[0] = (Math.exp(6*a)+Math.exp(-6*a))/2;
        double Fungsi=0;
        double es = 0.5 * Math.pow(10, 2-n);
        for(int i=1; i<=100000; i++){
            if(a==0){
                f[i]=f[i-1] + Math.pow(6*x,2*i)/faktorial(2*i);
            }else{
                f[i]=f[i-1] + (( Math.exp(6*a) + Math.pow(-1,i)*Math.exp(-6*a))*(Math.pow(6,i)*Math.pow(x-a,i)))/(2*(faktorial(i)));
            }
            double ea = ((f[i]-f[i-1])/f[i])*100;
            if(Math.abs(ea)<es){
                Fungsi += f[i];
            break;
            }
        }
        double Output = Math.floor(Fungsi*100000)/100000;
        return Output;
    }
    public static double PerhitunganSoal4(double a, double n, double x) {
        double[] f = new double[100001];
        f[0] = Math.log(-a);
        double Fungsi=0;
        double es = 0.5 * Math.pow(10, 2-n);
        for(int i=1; i<=100000; i++){
            f[i]=f[i-1] + (Math.pow(-1,i+1)*Math.pow(x-a, i))/(i*Math.pow(a,i));
            double ea = ((f[i]-f[i-1])/f[i])*100;
            if(Math.abs(ea)<es){
                Fungsi += f[i];
                System.out.println(i);
                break;
            }
        }
        double Output = Math.floor(Fungsi*100000)/100000;
        return Output;
    }
    public static double PerhitunganSoal5(double a, double n, double x) {
        double[] f = new double[100001];
        f[0] = a/(1-a);
        double Fungsi=0;
        double es = 0.5 * Math.pow(10, 2-n);
        for(int i=1; i<=100000; i++){
            f[i]=f[i-1]+deret(x, a, i);
            double ea = ((f[i]-f[i-1])/f[i])*100;
            if(Math.abs(ea)<es){
                Fungsi += f[i];
                System.out.println(i);
                break;
            }
        }
        double Output = Math.floor(Fungsi*100000)/100000;
        return Output;
    }
    public static double faktorial(int angka) {
        if(angka==1 || angka==0){
            return 1;
        }else{
            return angka*faktorial(angka-1);
        }
    }
    public static double deret(double x, double a, int suku) {
        double hasil = 1;
        for(int i=1; i<=suku; i++){
            hasil *=(x-a)/(1-a); 
        }
        return hasil;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Athaya_Aufa_Diaz_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Athaya_Aufa_Diaz_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Athaya_Aufa_Diaz_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Athaya_Aufa_Diaz_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Athaya_Aufa_Diaz_Tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField Masuka;
    private javax.swing.JTextField Masukn;
    private javax.swing.JTextField Masukx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> soal;
    private javax.swing.JTextField syaratnya;
    private javax.swing.JTextField wujudsoal;
    // End of variables declaration//GEN-END:variables
}
